Add files via upload

diff --git a/.github/workflows/Build_高通410 imm.yml b/.github/workflows/Build_高通410 imm.yml
--- a/.github/workflows/Build_高通410 imm.yml
+++ b/.github/workflows/Build_高通410 imm.yml
@@ -66,32 +66,61 @@ jobs:
         large-packages: false
         docker-images: false
         swap-storage: true
+
+    - name: Cache apt
+      uses: actions/cache@v5
+      with:
+        path: |
+          /var/cache/apt/archives
+          /var/lib/apt/lists
+        key: apt-${{ runner.os }}-${{ hashFiles('openwrt/.config') }}
+        restore-keys: |
+          apt-${{ runner.os }}-
         
     - name: Initialization environment
       env:
         DEBIAN_FRONTEND: noninteractive
       run: |
-        sudo -E apt-get -y update
-        sudo -E apt-get -y install $(curl -fsSL https://raw.githubusercontent.com/xuxin1955/depend_ubuntu2204_openwrt/refs/heads/main/depend_ubuntu2204_openwrt)
+        sudo -E apt-get -y update && sudo -E apt-get -y install --no-install-recommends $(curl -fsSL https://raw.githubusercontent.com/xuxin1955/depend_ubuntu2204_openwrt/refs/heads/main/depend_ubuntu2204_openwrt)
+
+    - name: Cache mkbootimg deb
+      uses: actions/cache@v5
+      with:
+        path: downloads/mkbootimg_34.0.5-12build1_all.deb
+        key: mkbootimg-34.0.5-12build1
+        restore-keys: |
+          mkbootimg-
 
     - name: mkbootimg build
       run: |
-        wget https://github.com/xuxin1955/depend_ubuntu2204_openwrt/releases/download/ubuntu_26.04_LTS_mkbootimg/mkbootimg_34.0.5-12build1_all.deb
-        sudo dpkg -i mkbootimg_34.0.5-12build1_all.deb
+        mkdir -p downloads
+        cd downloads
+
+        if [ ! -f mkbootimg_34.0.5-12build1_all.deb ]; then
+          echo "📥 mkbootimg deb not cached, downloading..."
+          wget https://github.com/xuxin1955/depend_ubuntu2204_openwrt/releases/download/ubuntu_26.04_LTS_mkbootimg/mkbootimg_34.0.5-12build1_all.deb
+        else
+          echo "✅ mkbootimg deb restored from cache"
+        fi
+
+        sudo dpkg -i mkbootimg_34.0.5-12build1_all.deb || true
         sudo apt-get install -f -y
-        # 验证安装
+
         mkbootimg --help || true
+
         MKBOOTIMG_PATH=$(which mkbootimg)
         if [ -n "$MKBOOTIMG_PATH" ]; then
-        echo "mkbootimg found at: $MKBOOTIMG_PATH"
-        file "$MKBOOTIMG_PATH"
+          echo "✅ mkbootimg found at: $MKBOOTIMG_PATH"
+          file "$MKBOOTIMG_PATH"
         else
-        echo "❌ mkbootimg not found in PATH!"
+          echo "❌ mkbootimg not found in PATH!"
         fi
 
         sudo timedatectl set-timezone "$TZ"
         sudo chmod 777 /mnt
         df -hT
+
+
         
     - name: Ensure Python build tools
       run: |
